name: Build and Test and Publish (main)

on:
  push:
    branches:
    - DEV

# We need some permissions to publish to Github Pages
permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
    - name: Run CI
      run: dotnet fsi build.fsx
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        #personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        force_orphan: true
#    - name: Publish NuGets (if main version changed)
#      run: dotnet nuget push "artifacts/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.FSHARP_FORMATTING_TOKEN_2020 }} --skip-duplicate
